/**
 * `tripwire canary create <type>` — the create command, covering both ordinary
 * canary types and AWS placements. Maps to `POST /canary`; the placement paths
 * render the returned one-time credential into a config block. The profile/label
 * name for a placement is generated by the backend and returned as `name`.
 */
import { chmodSync, writeFileSync } from "node:fs";

import { ApiError } from "../api/errors.js";
import { deliverToFile, deliverToStdout } from "../placements/deliver.js";
import { type PlacementDef, resolvePlacement } from "../placements/index.js";
import { resolveType, type TypeEntry } from "../types/registry.js";
import { CliError } from "../util/errors.js";
import { err, out } from "../util/io.js";
import type { Session } from "../util/session.js";

export interface CreateOptions {
  /** Positional type or placement id (the only way to name the type). */
  type?: string;
  note?: string;
  output?: string;
}

export async function runCreate(session: Session, opts: CreateOptions): Promise<void> {
  const typeInput = opts.type;
  if (!typeInput) {
    throw new CliError(
      "a canary type is required. run `tripwire canary create --help` for the list.",
    );
  }

  const placement = resolvePlacement(typeInput);
  if (placement) {
    await runPlacementCreate(session, placement, opts);
    return;
  }
  await runTypeCreate(session, resolveType(typeInput), opts);
}

/** Ordinary create: mint the canary and print only its credential fields. */
async function runTypeCreate(
  session: Session,
  entry: TypeEntry,
  opts: CreateOptions,
): Promise<void> {
  const payload: Record<string, unknown> = { type: entry.wire };
  if (opts.note) payload["memo"] = opts.note;

  const result = await createOrExplain(session, payload, entry.waitSeconds);

  if (opts.output) {
    writeJsonReveal(result, opts.output);
    return;
  }
  printReveal(entry, result);
}

/** Placement create: mint the underlying canary and render it into a config block. */
async function runPlacementCreate(
  session: Session,
  placement: PlacementDef,
  opts: CreateOptions,
): Promise<void> {
  const entry = resolveType(placement.underlyingType);

  const payload: Record<string, unknown> = { type: entry.wire };
  if (opts.note) payload["memo"] = opts.note;

  const result = await createOrExplain(session, payload, entry.waitSeconds);

  const accessKeyId = str(result["access_key_id"]);
  const secretAccessKey = str(result["secret_access_key"]);
  const region = str(result["region"]);
  if (!accessKeyId || !secretAccessKey) {
    // Safety valve: the canary was minted but we cannot render the block. Never
    // drop the one-time secret — dump the raw response, then error.
    err("!! could not render the block; the canary was minted, raw response below.");
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    throw new CliError("could not render the placement block; the raw response was printed above.");
  }

  // The profile/label name is generated by the backend and returned as `name`.
  const name = str(result["name"]) || str(result["id"]);
  const block = placement.render(name, { accessKeyId, secretAccessKey, region });
  const label = block.split("\n", 1)[0] ?? `[${name}]`;

  if (opts.output) {
    deliverToFile(block, opts.output, label);
  } else {
    deliverToStdout(block);
  }
}

/**
 * Run `POST /canary`, translating the create-specific failures (a still-
 * provisioning orphan; a hard provisioning failure) into actionable messages.
 */
async function createOrExplain(
  session: Session,
  payload: Record<string, unknown>,
  waitSeconds: number,
): Promise<Record<string, unknown>> {
  try {
    const client = await session.authedClient();
    return await client.createCanary(payload, waitSeconds * 1000);
  } catch (error) {
    if (error instanceof ApiError) {
      const message = createErrorMessage(error);
      if (message !== null) throw new CliError(message);
    }
    throw error;
  }
}

/** Friendly text for create-specific failures, or `null` to fall through. */
export function createErrorMessage(error: ApiError): string | null {
  if (error.status === 429 && error.detail === "canary_pending") {
    return (
      "the canary is still being prepared, so its one-time credential was not " +
      "returned. creating again would make a second one; instead find it with " +
      "`tripwire canary list`, delete it with `tripwire canary delete <id>`, then retry."
    );
  }
  if (error.status === 502 && error.detail === "provisioning_failed") {
    return "the canary could not be created; nothing was issued. please try again.";
  }
  return null;
}

/** Print only the credential fields for an ordinary create. */
function printReveal(entry: TypeEntry, result: Record<string, unknown>): void {
  for (const field of entry.outputFields) {
    const value = result[field];
    if (value !== undefined && value !== null && value !== "") {
      out(`${field}: ${String(value)}`);
    }
  }
}

/**
 * Write the full create JSON to `outputPath` (mode 0600). The WRITE and the
 * CHMOD are handled separately: if the write fails, dump the JSON to stdout with
 * a warning (post-mint safety valve); if only the chmod fails, warn about perms
 * without re-dumping the secret.
 */
function writeJsonReveal(result: Record<string, unknown>, outputPath: string): void {
  const text = `${JSON.stringify(result, null, 2)}\n`;
  try {
    writeFileSync(outputPath, text, { mode: 0o600 });
  } catch (writeError) {
    const reason = writeError instanceof Error ? writeError.message : String(writeError);
    err(`!! could not write to ${outputPath}: ${reason}; the credential is below.`);
    process.stdout.write(text);
    return;
  }
  try {
    chmodSync(outputPath, 0o600);
    err(`wrote ${outputPath}`);
  } catch (chmodError) {
    const reason = chmodError instanceof Error ? chmodError.message : String(chmodError);
    err(`wrote ${outputPath}, but could not set mode 0600 (${reason}); run: chmod 600 ${outputPath}`);
  }
}

function str(value: unknown): string {
  return value === undefined || value === null ? "" : String(value);
}
